### ISSUE TITLE
Error: invalid instruction suffix for `push'

### ISSUE THREAD

**Issue by anta40** [wind2412/wind_os#1]
I'm using 64-bit Ubuntu.
So I edited the Makefile and remove all `i386-elf-` prefixes. This is what I got when calling make.

> idt/intr.S:71: Warning: division by zero
> idt/intr.S:71: Error: junk `千！！万！！别！！忘！！了！！加！！上！！$！！否则会反汇编为pushl 0x1，乍一看好像没问题...但是gas会把0x1地址的东西压进去，神坑啊！！' after expression
> idt/intr.S:71: Error: invalid instruction suffix for `push'
> idt/intr.S:72: Error: bad expression
> idt/intr.S:72: Warning: division by zero
> idt/intr.S:72: Error: junk `千！！万！！别！！忘！！了！！加！！上！！$！！否则会反汇编为pushl 0x1，乍一看好像没问题...但是gas会把0x1地址的东西压进去，神坑啊！！' after expression
> idt/intr.S:72: Error: invalid instruction suffix for `push'
> idt/intr.S:73: Error: bad expression
> idt/intr.S:73: Warning: division by zero
> idt/intr.S:73: Error: junk `千！！万！！别！！忘！！了！！加！！上！！$！！否则会反汇编为pushl 0x1，乍一看好像没问题...但是gas会把0x1地址的东西压进去，神坑啊！！' after expression
> idt/intr.S:73: Error: invalid instruction suffix for `push'
> idt/intr.S:74: Error: bad expression
> idt/intr.S:74: Warning: division by zero
> idt/intr.S:74: Error: junk `千！！万！！别！！忘！！了！！加！！上！！$！！否则会反汇编为pushl 0x1，乍一看好像没问题...但是gas会把0x1地址的东西压进去，神坑啊！！' after expression
> idt/intr.S:74: Error: invalid instruction suffix for `push'
> idt/intr.S:76: Error: invalid instruction suffix for `push'
> idt/intr.S:76: Error: invalid instruction suffix for `push'
> idt/intr.S:77: Error: invalid instruction suffix for `push'

**Comment by wind2412** [comment]
Thank you for the issue! Bug fixed. It's only a toy project so that the code comments are very informal  -) Hope they didn't bother you.
